image:  python:3.12.4

before-script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source .venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - pytest tests/


